version: "2"
name: nodejs-outbox

services:
  rabbitmq:
    build:
      context: ./.docker/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 5552:5552
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_DEFAULT_USER: root

  order-db:
    build:
      context: ./.docker/order-db
      dockerfile: Dockerfile
    container_name: order-db
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U postgres -d orderdb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderdb

  shipment-db:
    build:
      context: ./.docker/shipment-db
      dockerfile: Dockerfile
    container_name: shipment-db
    ports:
      - 5433:5432
    healthcheck:
      test: "pg_isready -U postgres -d shipmentdb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shipmentdb

  debezium-server:
    build:
      context: ./.docker/debezium
      dockerfile: Dockerfile
    container_name: debezium-server
    ports:
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      order-db:
        condition: service_started
    environment:
      - DATABASE_HOSTNAME=order-db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=orderdb
      - DATABASE_SCHEMA=orders
      - DATABASE_OUTBOX_TABLE=outboxevent
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=root

  order-service:
    build:
      context: .
      dockerfile: ./.docker/order-service/Dockerfile
    container_name: order-service
    ports:
      - 3000:3000
    depends_on:
      debezium-server:
        condition: service_started
      order-db:
        condition: service_healthy
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - SERVER_PORT=3000
      - DB_NAME=orderdb
      - DB_SCHEMA=order
      - DB_PORT=5432
      - DB_HOST=order-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DEBUG=true

  shipment-service:
    build:
      context: .
      dockerfile: ./.docker/shipment-service/Dockerfile
    container_name: shipment-service
    ports:
      - 3001:3000
    depends_on:
      debezium-server:
        condition: service_started
      shipment-db:
        condition: service_healthy
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - SERVER_PORT=3001
      - DB_NAME=shipmentdb
      - DB_SCHEMA=shipments
      - DB_PORT=5432
      - DB_HOST=shipment-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DEBUG=true
