version: '3'

tasks:
  build:
    cmds:
      - docker compose build

  up:
    cmds:
      - docker compose up

  bootstrap:
    cmds:
      - docker compose up --build

  create-order:
    cmds:
      - >
        curl -X POST -H "Content-Type: application/json" --data @./resources/data/create-order-request.json http://localhost:3000/orders

  cancel-order-line:
    cmds:
      - >
        curl -X PUT -H "Content-Type: application/json" --data @./resources/data/cancel-order-line-request.json http://localhost:3000/orders/{{.ORDER_ID}}/lines/{{.ORDER_LINE_ID}}

  shipment-service-logs:
    cmds:
      - docker compose logs --follow shipment-service

  order-service-logs:
    cmds:
      - docker compose logs --follow order-service

  rabbitmq-logs:
    cmds:
      - docker compose logs --follow rabbitmq

  order-db-logs:
    cmds:
      - docker compose logs --follow order-db

  order-db-session:
    cmds:
      - docker compose run --rm order-db psql -d postgres://postgres:postgres@order-db/orderdb

  shipment-db-logs:
    cmds:
      - docker compose logs --follow shipment-db

  shipment-db-session:
    cmds:
      - docker compose run --rm shipment-db psql -d postgres://postgres:postgres@shipment-db/shipmentdb

  debezium-logs:
    cmds:
      - docker compose logs --follow debezium-server