version: '3'

tasks:
  build:
    cmds:
      - docker compose build

  up:
    cmds:
      - docker compose up

  bootstrap:
    cmds:
      - docker compose up --build

  create-order:
    cmds:
      - >
        curl -X POST -H "Content-Type: application/json" --data @./resources/data/create-order-request.json http://localhost:3000/orders

  cancel-order-line:
    cmds:
      - >
        curl -X PUT -H "Content-Type: application/json" --data @./resources/data/cancel-order-line-request.json http://localhost:3000/orders/1/lines/2